=== Tibblue/PRI/trabalho/TP-PRI_a78416_a79617/iBanda/resources/manifestoObra.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

  <xsd:element name="manifesto">
    <xsd:complexType><xsd:sequence>

      <xsd:element name="meta">
        <xsd:complexType>
          <xsd:all>
            <xsd:element name="utilizador" type="xsd:string"/>
          </xsd:all>
        </xsd:complexType>
      </xsd:element>

      <xsd:element name="json">
        <xsd:complexType><xsd:sequence>
          <xsd:element name="titulo" type="xsd:string"/>
          <xsd:element name="tipo" type="xsd:string"/>
          <xsd:element name="compositor" type="xsd:string" minOccurs="0"/>
          <xsd:element name="arranjo" type="xsd:string" minOccurs="0"/>
          <xsd:element name="instrumentos" maxOccurs="unbounded">
            <xsd:complexType><xsd:all>
              <xsd:element name="nome" type="xsd:string"/>
              <xsd:element name="partitura">
                <xsd:complexType><xsd:all>
                  <xsd:element name="path" type="xsd:string"/>
                  <xsd:element name="voz" type="xsd:string" minOccurs="0"/>
                  <xsd:element name="clave" type="xsd:string" minOccurs="0"/>
                  <xsd:element name="afinacao" type="xsd:string" minOccurs="0"/>
                </xsd:all></xsd:complexType>
              </xsd:element>
            </xsd:all></xsd:complexType>
          </xsd:element>
        </xsd:sequence></xsd:complexType>
      </xsd:element>

      <xsd:element name="files">
        <xsd:complexType><xsd:sequence>
          <xsd:element name="path" type="xsd:string" maxOccurs="unbounded"/>
        </xsd:sequence></xsd:complexType>
      </xsd:element>

    </xsd:sequence></xsd:complexType>
  </xsd:element>
</xsd:schema>

=== Tibblue/PRI/trabalho/TP-PRI_a78416_a79617/iBanda/resources/manifestoObra.xml
<?xml version="1.0" encoding="UTF-8"?>
<manifesto xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:noNamespaceSchemaLocation="manifestoObra.xsd">
    <meta>
        <utilizador>USER123</utilizador>
    </meta>
    <json>
        <titulo>TITULO</titulo>
        <tipo>TIPO</tipo>
        <compositor>COMPOSITOR</compositor>
        <arranjo></arranjo>
        <instrumentos>
            <nome>MAESTRO</nome>
            <partitura>
                <path>CMistico-maestro.pdf</path>
                <voz>VOZ</voz>
                <clave>CLAVE</clave>
                <afinacao>AFINACAO</afinacao>
            </partitura>
        </instrumentos>
        <instrumentos>
            <nome>SAX</nome>
            <partitura>
                <path>PDF2.pdf</path>
            </partitura>
        </instrumentos>
    </json>
    <files>
        <path>instrumentos/CMistico-maestro.pdf</path>
        <path>instrumentos/PDF2.pdf</path>
    </files>
</manifesto>
